use std::fs;
use tauri::Manager;

#[derive(serde::Deserialize, serde::Serialize)]
struct Cookie {
    domain: String,
    name: String,
    value: String,
    path: String,
    expires: Option<f64>,
    http_only: bool,
    secure: bool,
}

#[tauri::command]
async fn folder_picker_select() -> Result<Option<serde_json::Value>, String> {
    // In Tauri v2, file dialogs are handled differently
    // For now, return a simple implementation that can be extended later
    // You would typically use a frontend file picker or integrate with native dialogs
    Ok(None)
}

#[tauri::command]
async fn save_cookies(
    app: tauri::AppHandle,
    cookies: Vec<Cookie>,
    platform: String,
) -> Result<String, String> {
    // Get app data directory
    let app_data_dir = app.path().app_data_dir()
        .map_err(|e| format!("Failed to get app data dir: {}", e))?;

    // Create cookies directory if it doesn't exist
    let cookies_dir = app_data_dir.join("cookies");
    fs::create_dir_all(&cookies_dir)
        .map_err(|e| format!("Failed to create cookies dir: {}", e))?;

    // Create cookie file path
    let cookie_file = cookies_dir.join(format!("{}_cookies.txt", platform));

    // Convert cookies to Netscape format
    let mut netscape_content = String::from("# Netscape HTTP Cookie File\n");
    netscape_content.push_str("# This file was generated by Tauri App\n");
    netscape_content.push_str("# Edit at your own risk.\n\n");

    for cookie in cookies {
        // Netscape format: domain flag path secure expiration name value
        let domain = if cookie.domain.starts_with('.') {
            cookie.domain.clone()
        } else {
            format!(".{}", cookie.domain)
        };

        let flag = "TRUE"; // Include subdomains
        let path = cookie.path;
        let secure = if cookie.secure { "TRUE" } else { "FALSE" };
        let expiration = cookie.expires.unwrap_or(0.0) as i64;
        let name = cookie.name;
        let value = cookie.value;

        netscape_content.push_str(&format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            domain, flag, path, secure, expiration, name, value
        ));
    }

    // Write to file
    fs::write(&cookie_file, netscape_content)
        .map_err(|e| format!("Failed to write cookie file: {}", e))?;

    Ok(cookie_file.to_string_lossy().to_string())
}

#[tauri::command]
async fn get_cookie_file_path(
    app: tauri::AppHandle,
    platform: String,
) -> Result<String, String> {
    let app_data_dir = app.path().app_data_dir()
        .map_err(|e| format!("Failed to get app data dir: {}", e))?;

    let cookie_file = app_data_dir.join("cookies").join(format!("{}_cookies.txt", platform));

    if cookie_file.exists() {
        Ok(cookie_file.to_string_lossy().to_string())
    } else {
        Err(format!("Cookie file not found for {}", platform))
    }
}

#[tauri::command]
async fn open_login_window(
    app: tauri::AppHandle,
    platform: String,
) -> Result<(), String> {
    let url = match platform.as_str() {
        "instagram" => "https://www.instagram.com/accounts/login/",
        "tiktok" => "https://www.tiktok.com/login",
        _ => return Err("Unknown platform".to_string()),
    };

    let _window = tauri::WebviewWindowBuilder::new(
        &app,
        format!("{}-login", platform),
        tauri::WebviewUrl::External(url.parse().unwrap())
    )
    .title(format!("{} 로그인", platform))
    .inner_size(500.0, 700.0)
    .resizable(true)
    .build()
    .map_err(|e| format!("Failed to create window: {}", e))?;

    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
  tauri::Builder::default()
    .plugin(tauri_plugin_shell::init())
    .invoke_handler(tauri::generate_handler![
        folder_picker_select,
        save_cookies,
        get_cookie_file_path,
        open_login_window
    ])
    .setup(|app| {
      if cfg!(debug_assertions) {
        app.handle().plugin(
          tauri_plugin_log::Builder::default()
            .level(log::LevelFilter::Info)
            .build(),
        )?;
      }
      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
